name: Build

on: [push,pull_request]

jobs:
   build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        smalltalk: [ Pharo64-8.0 ]
        rdbms: [ MySQLv5.5, MySQLv5.6, MySQLv5.7, MariaDBv10.1, MariaDBv10.2, MariaDBv10.3, MariaDBv10.4,  MariaDBv10.5 ]
    name: ${{ matrix.smalltalk }} + ${{ matrix.rdbms }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Smalltalk CI
        uses: hpi-swa/setup-smalltalkCI@v1
        with:
          smalltalk-version: ${{ matrix.smalltalk }}
      - name: Install RDBMS
        run: ./scripts/setup-RDBMS.sh
        env:
          RDBMS: ${{ matrix.rdbms }}
      - name: Load Image and Run Tests
        run: smalltalkci -s ${{ matrix.smalltalk }}
        timeout-minutes: 15
        env:
          RDBMS: ${{ matrix.rdbms }}
      - run: echo "::set-env name=SCI_COVERAGE_FILE_LOCATION::${HOME}/.smalltalkCI/_builds/coveralls_results.json"
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.0.6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ${{ env.SCI_COVERAGE_FILE_LOCATION }}
